import {createConstants} from '../utils';

export default createConstants(
 'ADD_TO_BUILDER',
 'DELETE_FROM_BUILDER',
 'RECEIVE_ACTIVITIES',
 'RECEIVE_YELPS',
 'CONFIRM_REQUEST',
 'REORDER_UP',
 'REORDER_DOWN',
 'SAVE_TO_DB',
 'CHANGE_ROUTES',
 'RECEIVE_ROUTES',
 'LOGIN_USER_REQUEST',
 'LOGIN_USER_FAILURE',
 'LOGIN_USER_SUCCESS',
 'LOGOUT_USER',
 'SIGNUP_USER',
 'SIGNUP_USER_FAILURE',
 'SIGNUP_USER_REQUEST',
 'FETCH_PROTECTED_DATA_REQUEST',
 'RECEIVE_PROTECTED_DATA',
 'CHECK_AREA',
 'CHECK_CUISINE',
 'CHECK_BUDGET',
 'EDIT_DESC',
 'SAVE_CONFIRM_DB',
 'DELETE_CONFIRM_DB'
);
