import {createConstants} from '../utils';

export default createConstants(
 'ADD_TO_BUILDER',
 'DELETE_FROM_BUILDER',
 'RECEIVE_ACTIVITIES',
 'RECEIVE_YELPS',
 'CONFIRM_REQUEST',
 'REORDER_UP',
 'REORDER_DOWN',
 'SAVE_TO_DB',
 'CHANGE_ROUTES',
 'RECEIVE_ROUTES',
 'LOGIN_USER_REQUEST',
 'LOGIN_USER_FAILURE',
 'LOGIN_USER_SUCCESS',
 'LOGOUT_USER',
 'FETCH_PROTECTED_DATA_REQUEST',
 'RECEIVE_PROTECTED_DATA',
 'CHECK_CITY',
 'UNCHECK_CITY'
);
