export const ADD_TO_BUILDER = 'ADD_TO_BUILDER';
export const DELETE_FROM_BUILDER = 'DELETE_FROM_BUILDER';

export const RECEIVE_ACTIVITIES = 'RECEIVE_ACTIVITIES';
export const RECEIVE_YELPS = 'RECEIVE_YELPS';

export const CONFIRM_REQUEST = 'CONFIRM_REQUEST';
export const CONFIRM_SUCCESS = 'CONFIRM_SUCCESS';